new rawdata test cases
PulsarSearchSoft/astrotypes pull request #4
Opened 2020-04-15 08:54 UTC by arunnaidu123

Added additional data files for unit tests with few additional test cases and fixed the raw_data_file label issue.

2020-04-15 09:30 UTC, chrisjwilliams requested changes

2020-04-15 09:30 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/SigProcTestFile.h
> +        void file(std::string const& filename);
Why have this method? This class is supposed to be immutable reference info.

2020-04-15 09:30 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/SigProcTestFile.h
> +        void operator ++();
This interface is very fragile and exposes implementation details. For example the user has to know what the file ordering is to be able to use this class. If you decide to insert a new file in there their code will break.

2020-04-15 09:30 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/src/HeaderTest.cpp
> +    for(int i=0;i<3;i++)
this code could easily break as it makes assumptions about the SigProcFilterBankTestFile implementation.

2020-04-15 09:30 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/src/SigProcTestFile.cpp
> +{
A better way to do this is through inheritance. Its cheaper and more elegant.

2020-04-28 13:50 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/SigProcTestFile.h
> +        void operator ++();
not required for the present implementation. I have used TYPED_TEST.

2020-04-28 13:50 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/SigProcTestFile.h
> +        void file(std::string const& filename);
removed

2020-04-28 13:50 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/src/SigProcTestFile.cpp
> +{
Agreed.

2020-04-28 13:52 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/src/HeaderTest.cpp
> +    for(int i=0;i<3;i++)
I have used TYPED_TEST for this.

2020-05-01 11:05 UTC, chrisjwilliams reviewed
sould you restore the readme in the data dir. It should explain what the files are and point to the doc for your new templated for how to access them.

2020-05-01 11:05 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/SigProcTestFile.h
> +template <typename T>
Probably better not to have a default implementation as it can lead to runtime errors. e.g if someone uses SigProcFilterBankTestFile<long long>.

2020-05-01 11:05 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/src/HeaderTest.cpp
> +template <typename T>
definition lives in the .h file

2020-05-01 11:05 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/src/SigProcTestFile.cpp
> +    this->_start_time=typename units::ModifiedJulianClock::time_point() + units::julian_day(5000.0);
inefficientway of initialising - can't you jsut pass the julian days directly in the constructor?

2020-05-01 11:05 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/src/SigProcTestFile.cpp
>      this->_start_time=typename units::ModifiedJulianClock::time_point() + units::julian_day(5000.0);
ditto

2020-05-01 11:05 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/sigproc/test/src/HeaderTest.cpp
> +#include "gtest/gtest-typed-test.h"
move to header file

2020-05-01 14:23 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/SigProcTestFile.h
> +template <typename T>
Agreed. removed

2020-05-01 14:23 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/src/HeaderTest.cpp
> +template <typename T>
moved

2020-05-01 14:37 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/src/SigProcTestFile.cpp
> +    this->_start_time=typename units::ModifiedJulianClock::time_point() + units::julian_day(5000.0);
Done (I guess). I want to understand why this is inefficient.

2020-05-01 14:37 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/src/HeaderTest.cpp
> +#include "gtest/gtest-typed-test.h"
done

2020-05-01 14:37 UTC, arunnaidu123 commented on src/cpp/pss/astrotypes/sigproc/test/src/SigProcTestFile.cpp
>      this->_start_time=typename units::ModifiedJulianClock::time_point() + units::julian_day(5000.0);
Done (I guess)

2020-05-14 14:11 UTC, merged