ModuloOne class added, which returns the modulus of any input number …
PulsarSearchSoft/astrotypes pull request #6
Opened 2022-02-09 16:44 UTC by mitchmickaliger

…with one.

2022-02-21 12:55 UTC, chrisjwilliams requested changes

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> + * Copyright (c) 2018 PulsarSearchSoft
date should be 2022

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> +//#include <boost/units/quantity.hpp>
remove commented code

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> +        ModuloOne() = default;
ambiguous constructor. the defullt constructor and the value constructor with a default argument are the same!

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> + * Copyright (c) 2016 The SKA organisation
date

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> + */
missing include for std::fmod

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    _val = std::fmod(static_cast<T>(v), 1);
why are you recalculating fmod here? - we know we have an fmodded value

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    ++_val;
this will take it out of range. This operator will effectively do nothing for Modulo one. Suggests a buggy unit test.

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +ModuloOne<T> ModuloOne<T>::operator++(int)
this is also a null op. You can save some cycles by just returning a reference rather than a copy.

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    --_val;
should be a null op

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    ModuloOne<T> cpy(_val);
see previous commentss

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    return (*this)/static_cast<T>(v);
this could > 1.0

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    return (*this) /= static_cast<T>(v);
could go > 1.0

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/test/ModuloOneTest.h
> + * Copyright (c) 2016 The SKA organisation
date

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> + * Copyright (c) 2016 The SKA organisation
date

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ModuloOne<double> rv = mv++;  // mv = 1.7, rv = 0.7
mv = 1.7! that shouldn't happen - its of ModuloOne type

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_EQ(static_cast<int>(mv2), 1);
mv2 == 1?  But the doc says 0.0 is inclusive, 1.0 exclusive

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_FALSE(mv2 == mv);
you dont test the +ve == condition

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ModuloOne<double> mv(v1);
mark as const

2022-02-21 12:55 UTC, chrisjwilliams commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ModuloOne<double> mv2(v2);
mark as const

2022-02-21 13:46 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> + * Copyright (c) 2018 PulsarSearchSoft
done

2022-02-21 13:47 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> +//#include <boost/units/quantity.hpp>
done

2022-02-21 13:48 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> +        ModuloOne() = default;
default constructor removed

2022-02-21 13:48 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> + * Copyright (c) 2016 The SKA organisation
changed to 2022

2022-02-21 13:49 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> + */
cmath included

2022-02-21 13:57 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    _val = std::fmod(static_cast<T>(v), 1);
true; operator now just returns input value

2022-02-21 14:22 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    ++_val;
operator++() now just returns value of operand. Unit test modified to check if value of variable is same before and after increment operation

2022-02-21 14:24 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +ModuloOne<T> ModuloOne<T>::operator++(int)
operator++(int) now just returns value of operand. Unit test modified to check if value of variable is same before and after increment operation. Operator returns reference instead of copy now.

2022-02-21 14:27 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    --_val;
done

2022-02-21 14:27 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    ModuloOne<T> cpy(_val);
null op, returns ref

2022-02-21 16:50 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/ModuloOneTest.h
> + * Copyright (c) 2016 The SKA organisation
changed

2022-02-21 16:50 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> + * Copyright (c) 2016 The SKA organisation
changed

2022-02-21 16:53 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ModuloOne<double> rv = mv++;  // mv = 1.7, rv = 0.7
indeed; this was from before we sorted the return type issue. Now that is done, and I've fixed the increment and decrement operators to address your comments above, incrementing/decrementing now does essentially nothing, and the unit tests have been changed to verify this new behaviour.

2022-02-21 16:54 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_EQ(static_cast<int>(mv2), 1);
correct, fixed operator++() now has expected behaviour, unit tests changed to verify this

2022-02-21 16:59 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ModuloOne<double> mv(v1);
done

2022-02-21 16:59 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ModuloOne<double> mv2(v2);
done

2022-02-21 17:03 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_FALSE(mv2 == mv);
test added

2022-02-22 17:07 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    return (*this)/static_cast<T>(v);
return value now modded with 1

2022-02-22 17:41 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/detail/ModuloOne.cpp
> +    return (*this) /= static_cast<T>(v);
actually, this casts the ModuloOne to a double, then calls the /= operator, and the version of the /= operator that handles ModuloOne/double already mods the results of the division. Extra unit tests added to verify this is the case, though.

2022-02-23 13:29 UTC, chrisjwilliams approved these changes

2022-02-23 16:20 UTC, pulsarben requested changes

2022-02-23 16:20 UTC, pulsarben commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_FLOAT_EQ(static_cast<double>(mv3), 0.4);
Why float for double? Please add a comment to explain.

2022-02-23 16:20 UTC, pulsarben commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_FLOAT_EQ(static_cast<double>(mv), 0.1);
Refer to previous comment.

2022-02-23 16:20 UTC, pulsarben commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +            ASSERT_TRUE(mv < mv2);
i=0.9, j=0.4 so mv2 = 0.3 and mv=0.9 so how can mv < mv2? This should not pass.

2022-02-23 16:34 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_FLOAT_EQ(static_cast<double>(mv3), 0.4);
These should all be ASSERT_DOUBLE_EQ, as we are comparing doubles, not floats (ASSERT_FLOAT_EQ was the first of these functions I found, then I switched to ASSERT_DOUBLE_EQ, hence the mix). I will add a comment to all of these, as there are still standard ASSERT_EQs in some unit tests

2022-02-23 16:34 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_FLOAT_EQ(static_cast<double>(mv), 0.1);
see comment above

2022-02-23 17:34 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +    ASSERT_FLOAT_EQ(static_cast<double>(mv3), 0.4);
well, having said that, a few ASSERT_FLOAT_EQs are still required, as it seems ASSERT_DOUBLE_EQ compares too many decimal places (though not as many as ASSERT_EQ). Note, it seems gtest has moved away from these macros, and now uses ASSERT_THAT (which is too new for our gtest), though the user community still has issue with these new macros (regarding the same problem we're seeing here), but the gtest team are closing those tickets without replying (e.g. https://github.com/google/googletest/issues/2713 )... Anyway, I've updated the comments to explain the use of ASSERT_FLOAT_EQ when required

2022-02-24 16:03 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/test/src/ModuloOneTest.cpp
> +            ASSERT_TRUE(mv < mv2);
indeed, the operator<() needed a lot of work. I'll admit, I don't know what the math in that operator was trying to do (it was copied from panda); it seems overly complicated for what it's trying to do. This operator is now rewritten, and the unit tests have been changed and greatly expanded to test a range of scenarios.

2022-03-01 11:27 UTC, pulsarben approved these changes

2022-03-01 11:27 UTC, merged