Phase class added, which stores the phase of a revolution between [0.0, 1.0)
PulsarSearchSoft/astrotypes pull request #7
Opened 2022-02-23 11:00 UTC by mitchmickaliger

2022-03-01 12:22 UTC, pulsarben requested changes

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/Phase.h
> +#include <boost/units/conversion.hpp>
Is this include necessary?

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +typename multiply_typeof_helper<quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>, X>::type
Why is this here and not in ModuloOne.cpp?

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +typename multiply_typeof_helper<quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>, X>::type
Why is this here and not in ModuloOne.cpp?

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +operator/(const X& lhs, const quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>& rhs)
Shouldn't this also be in ModuloOne.cpp?

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +operator/(const quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>& lhs, const X& rhs)
Shouldn't this also be in ModuloOne.cpp?

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/test/src/PhaseTest.cpp
> +
Can we have a short comment for each test just outlining what it does?

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/test/src/PhaseTest.cpp
> +    Phase<double> p2(0.0 * revolution);
Should test that p1.value() returns 0 not 1.

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/test/src/PhaseTest.cpp
> +    ASSERT_FLOAT_EQ(phase.value(), Phase<double>(0.125 * revolution).value());
Only tests case where we have < 1 revolution. What is we have >1 rev? Can a test be added for this?

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/units/Time.h
> +// Determine if the templated type has a time dimension; if so, EnableIfIsTimeUnit will be aliased to type T
Need to add <type_traits> to allow this to work generally.

2022-03-01 12:22 UTC, pulsarben commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> +/*
We assume that changes here are already covered by the Modulo MR. Integrate with master and let us know :)

2022-03-01 14:27 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/Phase.h
> +#include <boost/units/conversion.hpp>
no, it was leftover from previous work; removed. Superfluous boost/units/base_units/angle/degree.hpp include also removed.

2022-03-01 14:41 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +typename multiply_typeof_helper<quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>, X>::type
no good reason; moved to ModuloOne.cpp

2022-03-01 14:42 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +typename multiply_typeof_helper<quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>, X>::type
Moved to ModuloOne.cpp

2022-03-01 14:42 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +operator/(const X& lhs, const quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>& rhs)
yes, moved

2022-03-01 14:42 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/detail/Phase.cpp
> +operator/(const quantity<Unit, pss::astrotypes::utils::ModuloOne<X>>& lhs, const X& rhs)
yes, moved

2022-03-01 18:13 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/test/src/PhaseTest.cpp
> +
Comments added to the top of each test

2022-03-01 18:17 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/test/src/PhaseTest.cpp
> +    Phase<double> p2(0.0 * revolution);
test added to check that p1 == 0

2022-03-01 18:55 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/test/src/PhaseTest.cpp
> +    ASSERT_FLOAT_EQ(phase.value(), Phase<double>(0.125 * revolution).value());
3 more tests added, including one where the input is greater than 1 revolution

2022-03-01 19:01 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/units/Time.h
> +// Determine if the templated type has a time dimension; if so, EnableIfIsTimeUnit will be aliased to type T
<type_traits> now #include'd

2022-03-01 19:03 UTC, mitchmickaliger commented on src/cpp/pss/astrotypes/utils/ModuloOne.h
> +/*
integration with master successful after a few conflicts

2022-03-03 11:28 UTC, pulsarben approved these changes

2022-03-03 11:28 UTC, merged